Do not build libevent samples
- Attempting to build libevent fails with "undefined reference to
  'raise'" on a Raspberry Pi 3 B+ in the sample directory. Some cursory
  searching indicates this may be due to certain build flags being
  elided (https://www.openwall.com/lists/musl/2018/05/09/4). Regardless,
  the samples are not needed for normal operation of libevent, so they
  have been disabled.